version: "2.1"

services:
  db:
    image: imhotek/mariadb:0.2.0
    environment:
      MYSQL_USER: super
      MYSQL_PASS: ${MYSQL_PASS}
      DB_NAME: opentickets
    healthcheck:
      test: ["CMD-SHELL", "nc -z localhost 3306"]
      interval: 2s
      retries: 10
      timeout: 1s

  webapp:
    image: imhotek/webapp:0.7.0
    ports:
      - 80
    volumes:
      - ./:/data
    depends_on:
      db:
        condition: service_healthy
